# Generated by Django 4.0.6 on 2022-07-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_image_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_file',
        ),
    ]
